version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values
      
  - name: orders
    description: information about orders 
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: addresses
    description: address information
  - name: events
    description: information about events
  - name: users
    description: user details like contact, address,name
  - name: order_items
    description: details about order_items
  - name: products
    description: details about company products
  - name: promos
    description: details about promotions
    
    
    
    
    